[build]
builder = "DOCKERFILE"
dockerfilePath = "services/ai-worker/Dockerfile"

[deploy]
startCommand = "node services/ai-worker/src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
