/**
 * Auto-generated SEO Metadata
 * Generated by Ailydian SEO Dashboard
 * Last updated: 2025-12-21T12:24:40.610Z
 */

import { Metadata } from 'next';

export const DOMAIN = 'www.ailydian.com';

// Primary keywords
export const PRIMARY_KEYWORDS = [
  "ailydian",
  "yapay zeka platformu türkiye",
  "enterprise ai platform multi language",
  "medical ai assistant turkish"
];

// Optimized metadata for all pages
export const DEFAULT_METADATA: Metadata = {
  metadataBase: new URL('https://www.ailydian.com'),

  // Title template
  title: {
    template: '%s | Ailydian',
    default: 'ailydian | Ailydian',
  },

  // Description
  description: 'ailydian nedir',

  // Keywords
  keywords: PRIMARY_KEYWORDS,

  // Authors
  authors: [{ name: 'Ailydian', url: 'https://www.ailydian.com' }],

  // Open Graph
  openGraph: {
    type: 'website',
    locale: 'tr_TR',
    url: 'https://www.ailydian.com',
    siteName: 'Ailydian',
    title: 'ailydian',
    description: 'ailydian nedir',
    images: [
      {
        url: 'https://www.ailydian.com/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Ailydian AI Platform',
      },
    ],
  },

  // Twitter
  twitter: {
    card: 'summary_large_image',
    title: 'ailydian',
    description: 'ailydian nedir',
    images: ['https://www.ailydian.com/og-image.png'],
  },

  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },

  // Verification
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
  },
};

// Language-specific metadata
export const LANGUAGE_METADATA = {
  'tr': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'tr',
    hreflang: 'tr-TR',
  },
  'en': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'en',
    hreflang: 'en-US',
  },
  'de': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'de',
    hreflang: 'de-DE',
  },
  'fr': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'fr',
    hreflang: 'fr-FR',
  },
  'es': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'es',
    hreflang: 'es-ES',
  },
  'ru': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'ru',
    hreflang: 'ru-RU',
  },
  'ar': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'ar',
    hreflang: 'ar-SA',
  },
  'zh': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'zh',
    hreflang: 'zh-CN',
  },
  'it': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'it',
    hreflang: 'it-IT',
  },
  'pt': {
    title: 'ailydian | Ailydian',
    description: 'ailydian nedir',
    lang: 'pt',
    hreflang: 'pt-PT',
  }
};

// Hreflang tags generator
export function getHreflangTags(currentPath: string = '/'): Array<{ rel: string; hreflang: string; href: string }> {
  const baseUrl = 'https://www.ailydian.com';
  const tags = [
    { rel: 'alternate', hreflang: 'x-default', href: baseUrl + currentPath },
  ];

  tags.push({ rel: 'alternate', hreflang: 'tr-TR', href: baseUrl + '/tr' + currentPath });
  tags.push({ rel: 'alternate', hreflang: 'en-US', href: baseUrl + '/en' + currentPath });
  tags.push({ rel: 'alternate', hreflang: 'de-DE', href: baseUrl + '/de' + currentPath });
  tags.push({ rel: 'alternate', hreflang: 'fr-FR', href: baseUrl + '/fr' + currentPath });
  tags.push({ rel: 'alternate', hreflang: 'es-ES', href: baseUrl + '/es' + currentPath });

  return tags;
}

// Schema.org structured data
export const ORGANIZATION_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'Ailydian',
  url: 'https://www.ailydian.com',
  logo: 'https://www.ailydian.com/logo.png',
  description: 'Advanced AI Platform',
  sameAs: [
    'https://twitter.com/ailydian',
    'https://linkedin.com/company/ailydian',
  ],
};
