/**
 * 🛡️ AILYDIAN SOC++ - MITRE ATT&CK Navigator Integration
 * Convert TTP heat map data to Navigator layer JSON format v13
 * Export/import Navigator layers with signature verification
 * © Emrah Şardağ. All rights reserved.
 */

import { TtpHeatMap } from './soc/schema';
import { mitreAttackEngine } from './soc/mitre';
import { PrismaClient } from '@prisma/client';
import crypto from 'crypto';

// Legacy compatibility interface
interface SecurityEvent {
  id: string;
  type: 'login' | 'trade' | 'withdrawal' | 'suspicious_activity';
  user_id: string;
  ip_address: string;
  user_agent: string;
  timestamp: string;
  metadata: Record<string, any>;
}

// MITRE ATT&CK Navigator Types
export interface NavigatorLayer {
  name: string;
  versions: {
    attack: string;
    navigator: string;
    layer: string;
  };
  domain: string;
  description: string;
  filters: {
    platforms: string[];
  };
  sorting: number;
  layout: {
    layout: string;
    showID: boolean;
    showName: boolean;
    showAggregateScores: boolean;
    countUnscored: boolean;
    aggregateFunction?: string;
  };
  techniques: NavigatorTechnique[];
  gradient: {
    colors: string[];
    minValue: number;
    maxValue: number;
  };
  legendItems: NavigatorLegendItem[];
  metadata: NavigatorMetadata[];
}

export interface LayerAnalysis {
  techniqueCount: number;
  scoredTechniqueCount: number;
  unscoredTechniqueCount: number;
  tacticsCoverage: string[];
  scoreStatistics: {
    min: number;
    max: number;
    average: number;
    total: number;
  };
  metadata: {
    layerName: string;
    domain: string;
    version: string;
  };
}

export interface NavigatorTechnique {
  techniqueID: string;
  tactic: string;
  score: number;
  color?: string;
  comment: string;
  enabled: boolean;
  metadata: NavigatorMetadata[];
  links: NavigatorLink[];
  showSubtechniques: boolean;
}

export interface NavigatorMetadata {
  name: string;
  value: string;
}

export interface NavigatorLink {
  label: string;
  url: string;
}

export interface NavigatorLegendItem {
  label: string;
  color: string;
}

export interface NavigatorExportOptions {
  name?: string;
  description?: string;
  timeRange?: '24h' | '72h' | '7d' | '30d';
  includeSubtechniques?: boolean;
  scoreMethod?: 'composite' | 'risk' | 'frequency' | 'confidence';
  colorScheme?: 'red' | 'blue' | 'green' | 'purple' | 'custom';
  platforms?: string[];
  showAggregateScores?: boolean;
  countUnscored?: boolean;
}

export interface SignedExport {
  url: string;
  signature: string;
  expiresAt: Date;
  layerId: string;
  metadata: {
    techniqueCount: number;
    mitreVersion: string;
    exportTime: Date;
  };
}

/**
 * MITRE ATT&CK Navigator Layer Generator
 */
export class NavigatorLayerGenerator {
  private readonly mitreVersion = '13.1';
  private readonly defaultPlatforms = ['windows', 'macos', 'linux', 'web', 'cloud'];
  
  /**
   * Convert TTP heat map to Navigator layer
   */
  generateLayer(
    heatMap: TtpHeatMap[],
    options: NavigatorExportOptions = {}
  ): NavigatorLayer {
    const {
      name = `AILYDIAN SOC Detection - ${new Date().toISOString().split('T')[0]}`,
      description = 'Generated by AILYDIAN Security Operations Center',
      scoreMethod = 'composite',
      colorScheme = 'red',
      platforms = this.defaultPlatforms,
      includeSubtechniques = false,
    } = options;

    // Generate techniques array
    const techniques = this.generateTechniques(heatMap, scoreMethod, colorScheme);
    
    // Calculate score range for gradient
    const scores = techniques.map(t => t.score);
    const minScore = Math.min(...scores, 0);
    const maxScore = Math.max(...scores, 1);

    // Generate color gradient
    const gradient = this.generateGradient(colorScheme, minScore, maxScore);
    
    // Generate legend items
    const legendItems = this.generateLegend(colorScheme, scoreMethod);

    const layer: NavigatorLayer = {
      name,
      versions: {
        attack: '13',
        navigator: '4.9.1',
        layer: '4.5'
      },
      domain: 'enterprise-attack',
      description,
      filters: {
        platforms,
      },
      sorting: 0,
      layout: {
        layout: 'side',
        aggregateFunction: 'average',
        showID: false,
        showName: true,
        showAggregateScores: false,
        countUnscored: false,
      },
      techniques,
      gradient,
      legendItems,
      metadata: [
        { name: 'MITRE Version', value: this.mitreVersion },
        { name: 'Generated By', value: 'AILYDIAN SOC' },
        { name: 'Generation Time', value: new Date().toISOString() },
        { name: 'Technique Count', value: techniques.length.toString() },
        { name: 'Score Method', value: scoreMethod },
      ],
    };

    return layer;
  }

  /**
   * Validate Navigator layer structure
   */
  validateLayer(layer: any): { isValid: boolean; errors: string[] } {
    const errors: string[] = [];

    // Check required fields
    if (!layer.name) errors.push('Layer name is required');
    if (!layer.versions || !layer.versions.navigator) errors.push('Navigator version is required');
    if (!layer.versions.layer) errors.push('Layer version is required');
    if (!layer.domain) errors.push('Domain is required');
    if (!Array.isArray(layer.techniques)) errors.push('Techniques must be an array');

    // Validate techniques
    if (layer.techniques) {
      layer.techniques.forEach((tech: any, index: number) => {
        if (!tech.techniqueID) {
          errors.push(`Technique ${index}: techniqueID is required`);
        }
        if (tech.score !== undefined && (typeof tech.score !== 'number' || tech.score < 0 || tech.score > 100)) {
          errors.push(`Technique ${index}: score must be a number between 0-100`);
        }
      });
    }

    return {
      isValid: errors.length === 0,
      errors
    };
  }

  /**
   * Analyze Navigator layer
   */
  analyzeLayer(layer: any): LayerAnalysis {
    const techniques = layer.techniques || [];
    const tacticsCovered = new Set();
    let minScore = Infinity;
    let maxScore = -Infinity;
    let totalScore = 0;
    let scoredTechniques = 0;

    techniques.forEach((tech: any) => {
      // Extract tactic from technique ID (simplified)
      const tactic = this.getTacticFromTechnique(tech.techniqueID);
      if (tactic) tacticsCovered.add(tactic);

      if (typeof tech.score === 'number') {
        minScore = Math.min(minScore, tech.score);
        maxScore = Math.max(maxScore, tech.score);
        totalScore += tech.score;
        scoredTechniques++;
      }
    });

    return {
      techniqueCount: techniques.length,
      scoredTechniqueCount: scoredTechniques,
      unscoredTechniqueCount: techniques.length - scoredTechniques,
      tacticsCoverage: Array.from(tacticsCovered) as string[],
      scoreStatistics: {
        min: minScore === Infinity ? 0 : minScore,
        max: maxScore === -Infinity ? 0 : maxScore,
        average: scoredTechniques > 0 ? totalScore / scoredTechniques : 0,
        total: totalScore
      },
      metadata: {
        layerName: layer.name,
        domain: layer.domain,
        version: layer.versions?.layer || 'unknown'
      }
    };
  }

  /**
   * Get tactic from technique ID (simplified mapping)
   */
  private getTacticFromTechnique(techniqueId: string): string | null {
    // This is a simplified mapping - in production, use full MITRE data
    const tacticMap: Record<string, string> = {
      'T1566': 'Initial Access',
      'T1078': 'Defense Evasion',
      'T1055': 'Defense Evasion',
      'T1027': 'Defense Evasion',
      'T1059': 'Execution',
      'T1543': 'Persistence',
      'T1105': 'Command and Control',
      'T1083': 'Discovery',
      'T1082': 'Discovery',
      'T1033': 'Discovery'
    };

    // Extract base technique ID (remove sub-technique part)
    const baseTechnique = techniqueId.split('.')[0];
    return tacticMap[baseTechnique] || null;
  }

  /**
   * Generate Navigator techniques from heat map
   */
  private generateTechniques(
    heatMap: TtpHeatMap[],
    scoreMethod: string,
    colorScheme: string
  ): NavigatorTechnique[] {
    const techniques: NavigatorTechnique[] = [];

    for (const item of heatMap) {
      const technique = mitreAttackEngine.getTechnique(item.ttp);
      if (!technique) continue;

      // Calculate score based on method
      let score = 0;
      switch (scoreMethod) {
        case 'composite':
          score = item.compositeScore || 0;
          break;
        case 'risk':
          score = item.avgRisk / 100; // Normalize to 0-1
          break;
        case 'frequency':
          score = Math.min((item.frequency || 0) / 10, 1); // Cap at 10 events/hour = 1.0
          break;
        case 'confidence':
          score = item.avgConfidence || 0;
          break;
      }

      // Generate color based on score
      const color = this.generateTechniqueColor(score, colorScheme);

      // Generate comment with context
      const comment = this.generateTechniqueComment(item, scoreMethod);

      techniques.push({
        techniqueID: item.ttp,
        tactic: technique.tactic[0] || 'Unknown',
        score,
        color,
        comment,
        enabled: true,
        metadata: [
          { name: 'Detection Count', value: item.count.toString() },
          { name: 'Avg Risk Score', value: `${Math.round(item.avgRisk)}/100` },
          { name: 'Last Seen', value: item.lastSeen.toISOString().split('T')[0] },
          { name: 'Composite Score', value: `${Math.round((item.compositeScore || 0) * 100)}/100` },
        ],
        links: [
          {
            label: 'MITRE ATT&CK',
            url: `https://attack.mitre.org/techniques/${item.ttp}`,
          },
          {
            label: 'AILYDIAN SOC Details',
            url: `/security/ttp?technique=${item.ttp}`,
          },
        ],
        showSubtechniques: false,
      });
    }

    return techniques.sort((a, b) => b.score - a.score);
  }

  /**
   * Generate technique-specific color based on score
   */
  private generateTechniqueColor(score: number, colorScheme: string): string {
    const intensity = Math.min(score, 1);
    
    switch (colorScheme) {
      case 'red':
        // Red gradient: light red to dark red
        const redValue = Math.round(255 - intensity * 100);
        return `#${redValue.toString(16).padStart(2, '0')}0000`;
      
      case 'blue':
        const blueValue = Math.round(255 - intensity * 100);
        return `#0000${blueValue.toString(16).padStart(2, '0')}`;
      
      case 'green':
        const greenValue = Math.round(255 - intensity * 100);
        return `#00${greenValue.toString(16).padStart(2, '0')}00`;
      
      case 'purple':
        const purpleRed = Math.round(128 + intensity * 127);
        const purpleBlue = Math.round(128 + intensity * 127);
        return `#${purpleRed.toString(16).padStart(2, '0')}00${purpleBlue.toString(16).padStart(2, '0')}`;
      
      default:
        // Heat map: yellow to red
        if (intensity < 0.5) {
          const yellow = Math.round(255 * intensity * 2);
          return `#${yellow.toString(16).padStart(2, '0')}${yellow.toString(16).padStart(2, '0')}00`;
        } else {
          const red = Math.round(255 * (intensity - 0.5) * 2);
          return `#ff${(255 - red).toString(16).padStart(2, '0')}00`;
        }
    }
  }

  /**
   * Generate technique comment with context
   */
  private generateTechniqueComment(item: TtpHeatMap, scoreMethod: string): string {
    const parts = [
      `${item.count} detections`,
      `Risk: ${Math.round(item.avgRisk)}/100`,
    ];

    if (item.frequency !== undefined) {
      parts.push(`${item.frequency.toFixed(1)} events/hour`);
    }

    if (item.avgConfidence !== undefined) {
      parts.push(`Confidence: ${Math.round(item.avgConfidence * 100)}%`);
    }

    const daysSince = Math.floor(
      (Date.now() - item.lastSeen.getTime()) / (24 * 60 * 60 * 1000)
    );
    
    if (daysSince === 0) {
      parts.push('Active today');
    } else if (daysSince === 1) {
      parts.push('Last seen yesterday');
    } else {
      parts.push(`Last seen ${daysSince} days ago`);
    }

    return parts.join(' | ');
  }

  /**
   * Generate color gradient configuration
   */
  private generateGradient(
    colorScheme: string,
    minValue: number,
    maxValue: number
  ): { colors: string[]; minValue: number; maxValue: number } {
    let colors: string[];
    
    switch (colorScheme) {
      case 'red':
        colors = ['#ffffff', '#ffcccc', '#ff6666', '#cc0000'];
        break;
      case 'blue':
        colors = ['#ffffff', '#ccddff', '#6699ff', '#0033cc'];
        break;
      case 'green':
        colors = ['#ffffff', '#ccffcc', '#66cc66', '#006600'];
        break;
      case 'purple':
        colors = ['#ffffff', '#e6ccff', '#cc66ff', '#6600cc'];
        break;
      default:
        colors = ['#ffffff', '#ffffcc', '#ffff66', '#ffcc00', '#ff6600', '#cc0000'];
    }

    return {
      colors,
      minValue: Math.max(minValue, 0),
      maxValue: Math.min(maxValue, 1),
    };
  }

  /**
   * Generate legend items for the layer
   */
  private generateLegend(
    colorScheme: string,
    scoreMethod: string
  ): NavigatorLegendItem[] {
    const methodName = {
      composite: 'Composite Score',
      risk: 'Risk Score',
      frequency: 'Detection Frequency',
      confidence: 'Confidence Level',
    }[scoreMethod] || 'Score';

    const baseColor = colorScheme === 'red' ? '#ff6666' : 
                     colorScheme === 'blue' ? '#6699ff' :
                     colorScheme === 'green' ? '#66cc66' :
                     colorScheme === 'purple' ? '#cc66ff' : '#ffcc00';

    return [
      { label: `High ${methodName}`, color: baseColor },
      { label: `Medium ${methodName}`, color: this.lightenColor(baseColor, 0.3) },
      { label: `Low ${methodName}`, color: this.lightenColor(baseColor, 0.6) },
    ];
  }

  /**
   * Lighten a hex color by a factor
   */
  private lightenColor(hex: string, factor: number): string {
    const num = parseInt(hex.slice(1), 16);
    const r = Math.min(255, Math.floor((num >> 16) + (255 - (num >> 16)) * factor));
    const g = Math.min(255, Math.floor(((num >> 8) & 0x00ff) + (255 - ((num >> 8) & 0x00ff)) * factor));
    const b = Math.min(255, Math.floor((num & 0x0000ff) + (255 - (num & 0x0000ff)) * factor));
    
    return `#${(r << 16 | g << 8 | b).toString(16).padStart(6, '0')}`;
  }
}

/**
 * Navigator Export Manager with Signing
 */
export class NavigatorExportManager {
  private readonly signingSecret: string;
  private readonly prisma?: PrismaClient;
  
  constructor(prismaOrSecret?: PrismaClient | string) {
    if (typeof prismaOrSecret === 'string') {
      this.signingSecret = prismaOrSecret;
    } else {
      this.prisma = prismaOrSecret;
      this.signingSecret = process.env.NAV_EXPORT_SIGNING_SECRET || 'dev-signing-secret';
    }
  }

  /**
   * Create export with database storage
   */
  async createExport(layer: NavigatorLayer, options?: {
    includeSignature?: boolean;
    expirationHours?: number;
    metadata?: Record<string, any>;
  }): Promise<{ id: string; url: string; signature?: string; expiresAt?: Date }> {
    if (!this.prisma) {
      throw new Error('Prisma client required for createExport');
    }

    const layerId = this.generateLayerId();
    const layerData = JSON.stringify(layer, null, 2);
    
    // Create signature if requested
    let signature: string | undefined;
    if (options?.includeSignature !== false) {
      signature = crypto.createHmac('sha256', this.signingSecret)
        .update(layerData)
        .digest('hex');
    }

    // Calculate expiration
    const expiresAt = options?.expirationHours ? 
      new Date(Date.now() + options.expirationHours * 60 * 60 * 1000) : 
      undefined;

    // Store in database
    await this.prisma.navigatorExport.create({
      data: {
        id: layerId,
        timestamp: new Date(),
        layerData: JSON.stringify(layer),
        signature,
        mitreVersion: layer.versions.attack,
        techniqueCount: layer.techniques.length,
        expiresAt
      }
    });

    // Generate URL (in production this would be a cloud storage URL)
    const url = `/api/security/navigator/export?id=${layerId}`;

    return { id: layerId, url, signature, expiresAt };
  }

  /**
   * Get export by ID
   */
  async getExport(exportId: string): Promise<{
    id: string;
    layer: NavigatorLayer;
    signature?: string;
    createdAt: Date;
    expiresAt?: Date;
  } | null> {
    if (!this.prisma) {
      throw new Error('Prisma client required for getExport');
    }

    const exportData = await this.prisma.navigatorExport.findUnique({
      where: { id: exportId }
    });

    if (!exportData) {
      return null;
    }

    return {
      id: exportData.id,
      layer: JSON.parse(exportData.layerData as string) as NavigatorLayer,
      signature: exportData.signature || undefined,
      createdAt: exportData.createdAt,
      expiresAt: exportData.expiresAt || undefined
    };
  }

  /**
   * List exports
   */
  async listExports(options?: {
    limit?: number;
    offset?: number;
  }): Promise<Array<{
    id: string;
    timestamp: Date;
    techniqueCount: number;
    mitreVersion: string;
    expiresAt?: Date;
  }>> {
    if (!this.prisma) {
      throw new Error('Prisma client required for listExports');
    }

    const exports = await this.prisma.navigatorExport.findMany({
      take: options?.limit || 50,
      skip: options?.offset || 0,
      orderBy: { createdAt: 'desc' },
      select: {
        id: true,
        timestamp: true,
        techniqueCount: true,
        mitreVersion: true,
        expiresAt: true
      }
    });

    return exports.map(exp => ({
      id: exp.id,
      timestamp: exp.timestamp,
      techniqueCount: exp.techniqueCount,
      mitreVersion: exp.mitreVersion,
      expiresAt: exp.expiresAt || undefined
    }));
  }

  /**
   * Verify layer signature
   */
  verifySignature(layer: NavigatorLayer, signature: string): boolean {
    const layerData = JSON.stringify(layer, null, 2);
    const expectedSignature = crypto.createHmac('sha256', this.signingSecret)
      .update(layerData)
      .digest('hex');
    return signature === expectedSignature;
  }

  /**
   * Create signed export with URL
   */
  async createSignedExport(
    layer: NavigatorLayer,
    bucketUrl?: string
  ): Promise<SignedExport> {
    const layerId = this.generateLayerId();
    const layerData = JSON.stringify(layer, null, 2);
    
    // Generate signature
    const signature = this.signLayer(layerData);
    
    // Generate expiration (24 hours)
    const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000);
    
    // Generate signed URL (mock implementation - would integrate with real storage)
    const baseUrl = bucketUrl || process.env.NAV_EXPORT_BUCKET_URL || 'https://storage.ailydian.com';
    const url = `${baseUrl}/navigator/${layerId}.json?signature=${signature}&expires=${expiresAt.getTime()}`;

    return {
      url,
      signature,
      expiresAt,
      layerId,
      metadata: {
        techniqueCount: layer.techniques.length,
        mitreVersion: layer.metadata.find(m => m.name === 'MITRE Version')?.value || '13.1',
        exportTime: new Date(),
      },
    };
  }

  /**
   * Import and merge external Navigator layer
   */
  importLayer(layerData: string): {
    layer: NavigatorLayer;
    coverage: {
      newTechniques: string[];
      existingTechniques: string[];
      missingInCurrent: string[];
    };
  } {
    const layer: NavigatorLayer = JSON.parse(layerData);
    
    // Validate layer structure
    if (!this.validateLayer(layer)) {
      throw new Error('Invalid Navigator layer format');
    }

    // Calculate coverage compared to current KB
    const allTechniques = mitreAttackEngine.getAllTechniques().map((t: any) => t.id);
    const importedTechniques = layer.techniques.map(t => t.techniqueID);
    
    const coverage = {
      newTechniques: importedTechniques.filter(t => !allTechniques.includes(t)),
      existingTechniques: importedTechniques.filter(t => allTechniques.includes(t)),
      missingInCurrent: allTechniques.filter((t: string) => !importedTechniques.includes(t)),
    };

    return { layer, coverage };
  }

  /**
   * Generate unique layer ID
   */
  private generateLayerId(): string {
    return `layer_${Date.now()}_${crypto.randomBytes(8).toString('hex')}`;
  }

  /**
   * Sign layer data with HMAC
   */
  private signLayer(layerData: string): string {
    return crypto
      .createHmac('sha256', this.signingSecret)
      .update(layerData)
      .digest('hex');
  }

  /**
   * Validate Navigator layer structure
   */
  private validateLayer(layer: any): layer is NavigatorLayer {
    return (
      typeof layer === 'object' &&
      typeof layer.name === 'string' &&
      typeof layer.version === 'string' &&
      typeof layer.domain === 'string' &&
      Array.isArray(layer.techniques) &&
      layer.techniques.every((t: any) =>
        typeof t.techniqueID === 'string' &&
        typeof t.score === 'number' &&
        typeof t.enabled === 'boolean'
      )
    );
  }
}

// Export singleton instances
export const navigatorGenerator = new NavigatorLayerGenerator();
export const navigatorExporter = new NavigatorExportManager();

// Legacy compatibility - keeping original MITRENavigator for backward compatibility
// (The original code is preserved for any existing integrations)
export class MITRENavigator {
  private techniques: Map<string, any> = new Map();
  private tactics: Map<string, any> = new Map();

  constructor() {
    this.initializeATTCKData();
  }

  private initializeATTCKData() {
    // MITRE ATT&CK Tactics
    const tactics = [
      { id: 'TA0001', name: 'Initial Access', description: 'Trying to get into your network' },
      { id: 'TA0002', name: 'Execution', description: 'Trying to run malicious code' },
      { id: 'TA0003', name: 'Persistence', description: 'Trying to maintain their foothold' },
      { id: 'TA0004', name: 'Privilege Escalation', description: 'Trying to gain higher-level permissions' },
      { id: 'TA0005', name: 'Defense Evasion', description: 'Trying to avoid being detected' },
      { id: 'TA0006', name: 'Credential Access', description: 'Trying to steal account names and passwords' },
      { id: 'TA0007', name: 'Discovery', description: 'Trying to figure out your environment' },
      { id: 'TA0008', name: 'Lateral Movement', description: 'Trying to move through your environment' },
      { id: 'TA0009', name: 'Collection', description: 'Trying to gather data of interest' },
      { id: 'TA0010', name: 'Exfiltration', description: 'Trying to steal data' },
      { id: 'TA0011', name: 'Impact', description: 'Trying to manipulate, interrupt, or destroy data/systems' },
    ];

    tactics.forEach(tactic => this.tactics.set(tactic.id, tactic));

    // Key MITRE ATT&CK Techniques for Financial/Trading platforms
    const techniques = [
      // Initial Access
      { id: 'T1566.001', name: 'Spearphishing Attachment', tactic: 'TA0001', severity: 'high' },
      { id: 'T1566.002', name: 'Spearphishing Link', tactic: 'TA0001', severity: 'high' },
      { id: 'T1190', name: 'Exploit Public-Facing Application', tactic: 'TA0001', severity: 'critical' },
      { id: 'T1133', name: 'External Remote Services', tactic: 'TA0001', severity: 'medium' },

      // Execution
      { id: 'T1059.001', name: 'PowerShell', tactic: 'TA0002', severity: 'high' },
      { id: 'T1059.003', name: 'Windows Command Shell', tactic: 'TA0002', severity: 'medium' },
      { id: 'T1203', name: 'Exploitation for Client Execution', tactic: 'TA0002', severity: 'high' },

      // Persistence
      { id: 'T1547.001', name: 'Registry Run Keys / Startup Folder', tactic: 'TA0003', severity: 'medium' },
      { id: 'T1053.005', name: 'Scheduled Task', tactic: 'TA0003', severity: 'medium' },
      { id: 'T1078', name: 'Valid Accounts', tactic: 'TA0003', severity: 'critical' },

      // Privilege Escalation
      { id: 'T1548.002', name: 'Bypass User Account Control', tactic: 'TA0004', severity: 'medium' },
      { id: 'T1055', name: 'Process Injection', tactic: 'TA0004', severity: 'high' },

      // Defense Evasion
      { id: 'T1027', name: 'Obfuscated Files or Information', tactic: 'TA0005', severity: 'medium' },
      { id: 'T1055', name: 'Process Injection', tactic: 'TA0005', severity: 'high' },
      { id: 'T1562.001', name: 'Disable or Modify Tools', tactic: 'TA0005', severity: 'high' },

      // Credential Access
      { id: 'T1110', name: 'Brute Force', tactic: 'TA0006', severity: 'high' },
      { id: 'T1555', name: 'Credentials from Password Stores', tactic: 'TA0006', severity: 'high' },
      { id: 'T1539', name: 'Steal Web Session Cookie', tactic: 'TA0006', severity: 'critical' },

      // Discovery
      { id: 'T1082', name: 'System Information Discovery', tactic: 'TA0007', severity: 'low' },
      { id: 'T1083', name: 'File and Directory Discovery', tactic: 'TA0007', severity: 'low' },
      { id: 'T1087', name: 'Account Discovery', tactic: 'TA0007', severity: 'medium' },

      // Lateral Movement
      { id: 'T1021.001', name: 'Remote Desktop Protocol', tactic: 'TA0008', severity: 'medium' },
      { id: 'T1550.001', name: 'Application Access Token', tactic: 'TA0008', severity: 'high' },

      // Collection
      { id: 'T1560', name: 'Archive Collected Data', tactic: 'TA0009', severity: 'medium' },
      { id: 'T1113', name: 'Screen Capture', tactic: 'TA0009', severity: 'medium' },
      { id: 'T1125', name: 'Video Capture', tactic: 'TA0009', severity: 'low' },

      // Exfiltration
      { id: 'T1041', name: 'Exfiltration Over C2 Channel', tactic: 'TA0010', severity: 'critical' },
      { id: 'T1567.002', name: 'Exfiltration to Cloud Storage', tactic: 'TA0010', severity: 'high' },

      // Impact
      { id: 'T1486', name: 'Data Encrypted for Impact', tactic: 'TA0011', severity: 'critical' },
      { id: 'T1565.001', name: 'Stored Data Manipulation', tactic: 'TA0011', severity: 'critical' },
      { id: 'T1499', name: 'Endpoint Denial of Service', tactic: 'TA0011', severity: 'high' },
    ];

    techniques.forEach(technique => this.techniques.set(technique.id, technique));
  }

  // Generate MITRE Navigator Layer JSON
  generateNavigatorLayer(detectedTechniques: string[], title: string = 'AILYDIAN Security Detection'): any {
    const layer = {
      name: title,
      versions: {
        attack: '14',
        navigator: '4.9.1',
        layer: '4.5'
      },
      domain: 'enterprise-attack',
      description: `Security detections and threat landscape for ${title}`,
      filters: {
        platforms: ['Windows', 'macOS', 'Linux', 'Network', 'Web']
      },
      sorting: 0,
      layout: {
        layout: 'side',
        aggregateFunction: 'average',
        showID: true,
        showName: true,
        showAggregateScores: false,
        countUnscored: false
      },
      hideDisabled: false,
      techniques: [] as any[],
      gradient: {
        colors: [
          '#ff6666', // Critical
          '#ffb366', // High  
          '#ffe066', // Medium
          '#66ff66'  // Low
        ],
        minValue: 0,
        maxValue: 100
      },
      legendItems: [
        { label: 'Critical Risk', color: '#ff6666' },
        { label: 'High Risk', color: '#ffb366' },
        { label: 'Medium Risk', color: '#ffe066' },
        { label: 'Low Risk', color: '#66ff66' }
      ],
      metadata: [
        { name: 'Generated', value: new Date().toISOString() },
        { name: 'Platform', value: 'AILYDIAN AI Lens Trader' },
        { name: 'Environment', value: 'Trading Platform Security' }
      ]
    };

    // Add detected techniques with scoring
    layer.techniques = detectedTechniques.map(techniqueId => {
      const technique = this.techniques.get(techniqueId);
      if (!technique) return null;

      const score = this.getSeverityScore(technique.severity);
      const color = this.getSeverityColor(technique.severity);

      return {
        techniqueID: techniqueId,
        tactic: technique.tactic,
        score: score,
        color: color,
        comment: `Detected in AILYDIAN security monitoring - ${technique.name}`,
        enabled: true,
        metadata: [
          { name: 'Detection Time', value: new Date().toISOString() },
          { name: 'Severity', value: technique.severity },
          { name: 'Status', value: 'Active Monitoring' }
        ]
      };
    }).filter(Boolean);

    return layer;
  }

  // Export techniques mapping for current threats
  exportThreatMapping(events: SecurityEvent[]): any {
    const detectedTechniques = new Set<string>();
    const threatStats = {
      total_events: events.length,
      tactics_involved: new Set<string>(),
      severity_distribution: { critical: 0, high: 0, medium: 0, low: 0 },
      timeline: this.generateThreatTimeline(events)
    };

    // Analyze events and map to MITRE techniques
    events.forEach(event => {
      const techniques = this.mapEventToTechniques(event);
      techniques.forEach(technique => {
        detectedTechniques.add(technique);
        const techniqueData = this.techniques.get(technique);
        if (techniqueData) {
          threatStats.tactics_involved.add(techniqueData.tactic);
          threatStats.severity_distribution[techniqueData.severity as keyof typeof threatStats.severity_distribution]++;
        }
      });
    });

    return {
      navigator_layer: this.generateNavigatorLayer(Array.from(detectedTechniques)),
      threat_statistics: {
        ...threatStats,
        tactics_involved: Array.from(threatStats.tactics_involved)
      },
      detected_techniques: Array.from(detectedTechniques).map(id => ({
        id,
        ...this.techniques.get(id)
      })),
      recommendations: this.generateSecurityRecommendations(Array.from(detectedTechniques))
    };
  }

  private mapEventToTechniques(event: SecurityEvent): string[] {
    const techniques: string[] = [];

    switch (event.type) {
      case 'login':
        if (event.metadata.failed_attempts > 3) {
          techniques.push('T1110'); // Brute Force
        }
        if (event.metadata.unusual_location) {
          techniques.push('T1078'); // Valid Accounts (suspicious usage)
        }
        break;

      case 'trade':
        if (event.metadata.unusual_pattern) {
          techniques.push('T1565.001'); // Stored Data Manipulation
        }
        if (event.metadata.large_volume) {
          techniques.push('T1041'); // Exfiltration Over C2 Channel
        }
        break;

      case 'withdrawal':
        techniques.push('T1041'); // Exfiltration
        if (event.metadata.suspicious_address) {
          techniques.push('T1567.002'); // Exfiltration to Cloud Storage
        }
        break;

      case 'suspicious_activity':
        techniques.push('T1027'); // Obfuscated Files or Information
        if (event.metadata.automated_behavior) {
          techniques.push('T1059.001'); // PowerShell/Scripting
        }
        break;
    }

    return techniques;
  }

  private generateThreatTimeline(events: SecurityEvent[]): any {
    const timeline = events
      .sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime())
      .map(event => ({
        timestamp: event.timestamp,
        type: event.type,
        techniques: this.mapEventToTechniques(event),
        severity: this.getEventSeverity(event)
      }));

    return timeline;
  }

  private getEventSeverity(event: SecurityEvent): string {
    switch (event.type) {
      case 'withdrawal': return 'critical';
      case 'suspicious_activity': return 'high';
      case 'trade': return 'medium';
      case 'login': return 'low';
      default: return 'low';
    }
  }

  private getSeverityScore(severity: string): number {
    switch (severity) {
      case 'critical': return 100;
      case 'high': return 75;
      case 'medium': return 50;
      case 'low': return 25;
      default: return 0;
    }
  }

  private getSeverityColor(severity: string): string {
    switch (severity) {
      case 'critical': return '#ff6666';
      case 'high': return '#ffb366';
      case 'medium': return '#ffe066';
      case 'low': return '#66ff66';
      default: return '#cccccc';
    }
  }

  private generateSecurityRecommendations(techniques: string[]): string[] {
    const recommendations: string[] = [];
    const uniqueTactics = new Set<string>();

    techniques.forEach(techniqueId => {
      const technique = this.techniques.get(techniqueId);
      if (technique) {
        uniqueTactics.add(technique.tactic);
      }
    });

    // Generate recommendations based on detected tactics
    uniqueTactics.forEach(tacticId => {
      const tactic = this.tactics.get(tacticId);
      if (tactic) {
        switch (tacticId) {
          case 'TA0001': // Initial Access
            recommendations.push('Implement email security filtering and user awareness training');
            recommendations.push('Enable multi-factor authentication for all accounts');
            break;
          case 'TA0002': // Execution
            recommendations.push('Deploy application whitelisting and endpoint protection');
            recommendations.push('Monitor and restrict script execution');
            break;
          case 'TA0006': // Credential Access
            recommendations.push('Implement privileged access management (PAM)');
            recommendations.push('Enable account lockout policies and monitoring');
            break;
          case 'TA0010': // Exfiltration
            recommendations.push('Deploy data loss prevention (DLP) solutions');
            recommendations.push('Monitor network traffic for unusual patterns');
            break;
          case 'TA0011': // Impact
            recommendations.push('Implement backup and recovery procedures');
            recommendations.push('Deploy endpoint detection and response (EDR)');
            break;
        }
      }
    });

    return [...new Set(recommendations)]; // Remove duplicates
  }

  // Get technique details by ID
  getTechnique(id: string): any {
    return this.techniques.get(id);
  }

  // Get tactic details by ID
  getTactic(id: string): any {
    return this.tactics.get(id);
  }

  // Get all techniques for a specific tactic
  getTechniquesByTactic(tacticId: string): any[] {
    return Array.from(this.techniques.values()).filter(technique => technique.tactic === tacticId);
  }

  // Get threat coverage percentage
  getThreatCoverage(detectedTechniques: string[]): number {
    const totalTechniques = this.techniques.size;
    const detectedCount = detectedTechniques.length;
    return (detectedCount / totalTechniques) * 100;
  }
}
