#!/bin/bash
# Process Cleanup Script - Generated by Claude SRE Agent (2025-10-08)

echo "🧹 Cleaning up duplicate Node processes..."

# Kill all node server.js processes except PM2-managed ones
pkill -f "node server.js" 2>/dev/null || true

# Wait for processes to terminate
sleep 2

# Check remaining processes
REMAINING=$(ps aux | grep -E "node server.js" | grep -v "grep" | wc -l | tr -d ' ')

if [ "$REMAINING" -eq "0" ]; then
    echo "✅ All duplicate processes cleaned"
else
    echo "⚠️ Still $REMAINING processes running (might be PM2)"
fi

# List PM2 processes
echo ""
echo "📊 PM2 Status:"
pm2 list
