#!/bin/bash
# Rollback Script - Generated by Claude SRE Agent (2025-10-08)
set -e

echo "🔄 ROLLBACK INITIATED"
echo "Target: Previous Vercel deployment"

# Get previous deployment
PREV_DEPLOYMENT=$(vercel ls | grep Production | sed -n '2p' | awk '{print $1}')

if [ -z "$PREV_DEPLOYMENT" ]; then
    echo "❌ No previous deployment found"
    exit 1
fi

echo "📦 Rolling back to: $PREV_DEPLOYMENT"

# Promote previous deployment
vercel promote "$PREV_DEPLOYMENT" --yes

# Wait for propagation
sleep 10

# Verify
curl -sSf https://www.ailydian.com/api/health || (echo "❌ Rollback health check failed" && exit 1)

echo "✅ ROLLBACK COMPLETE"
