#!/bin/bash

# 🔐 AI PRIVACY PROTOCOL - 7-Layer Deep Scan
# Removes ALL AI traces from codebase (Claude, ChatGPT, Copilot, etc.)

set -e

echo "🔒 AI PRIVACY PROTOCOL v1.0 - Starting 7-Layer Deep Scan..."
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

TRACES_FOUND=0

# Layer 1: Code Content (AI Mentions)
echo "📋 Layer 1: Scanning code content for AI mentions..."
if grep -rn --include="*.js" --include="*.ts" --include="*.jsx" --include="*.tsx" \
  -E "(Generated by|Created by|Written by).*(Claude|GPT|Copilot|Anthropic|OpenAI)" . 2>/dev/null | grep -v node_modules | grep -v ".git"; then
  echo "⚠️  Found AI attribution in code!"
  TRACES_FOUND=$((TRACES_FOUND + 1))
else
  echo "✅ No AI attribution in code"
fi

# Layer 2: Git Commit Messages
echo ""
echo "📋 Layer 2: Scanning git commit messages..."
if git log --all --format="%s %b" | grep -iE "(Claude|GPT|Copilot|Anthropic|OpenAI|AI-generated|AI assisted)" | head -5; then
  echo "⚠️  Found AI mentions in git commits!"
  TRACES_FOUND=$((TRACES_FOUND + 1))
else
  echo "✅ No AI mentions in git commits"
fi

# Layer 3: Unicode Watermarks (Zero-Width Characters)
echo ""
echo "📋 Layer 3: Scanning for Unicode watermarks..."
if grep -rn --include="*.js" --include="*.ts" --include="*.md" \
  -P "[\x{200B}\x{200C}\x{200D}\x{FEFF}]" . 2>/dev/null | grep -v node_modules | grep -v ".git" | head -5; then
  echo "⚠️  Found Unicode zero-width characters!"
  TRACES_FOUND=$((TRACES_FOUND + 1))
else
  echo "✅ No Unicode watermarks found"
fi

# Layer 4: File Metadata (Git Author)
echo ""
echo "📋 Layer 4: Checking git authorship..."
if git log --all --format="%an %ae" | grep -iE "(Claude|Anthropic|OpenAI)" | head -5; then
  echo "⚠️  Found AI in git authorship!"
  TRACES_FOUND=$((TRACES_FOUND + 1))
else
  echo "✅ No AI in git authorship"
fi

# Layer 5: Package.json AI References
echo ""
echo "📋 Layer 5: Scanning package.json..."
if grep -iE "(Claude|GPT|Copilot|Anthropic|OpenAI)" package.json 2>/dev/null; then
  echo "⚠️  Found AI references in package.json!"
  TRACES_FOUND=$((TRACES_FOUND + 1))
else
  echo "✅ No AI references in package.json"
fi

# Layer 6: README and Documentation
echo ""
echo "📋 Layer 6: Scanning README and docs..."
if grep -rn --include="README*.md" --include="*.md" \
  -iE "(Generated by|Created by|Powered by).*(Claude|GPT|Copilot)" . 2>/dev/null | grep -v node_modules | head -5; then
  echo "⚠️  Found AI attribution in documentation!"
  TRACES_FOUND=$((TRACES_FOUND + 1))
else
  echo "✅ No AI attribution in documentation"
fi

# Layer 7: .claude and AI Config Files
echo ""
echo "📋 Layer 7: Checking for AI config files..."
AI_CONFIG_FILES=(".claude" ".clauderc" ".copilot" ".cursor" ".aider" ".continue")
for config in "${AI_CONFIG_FILES[@]}"; do
  if [ -e "$config" ]; then
    echo "⚠️  Found AI config: $config"
    TRACES_FOUND=$((TRACES_FOUND + 1))
  fi
done

if [ $TRACES_FOUND -eq 0 ]; then
  echo ""
  echo "✅ DEPLOYMENT READY - No AI traces found!"
  echo "   Code is indistinguishable from human-written code."
  exit 0
else
  echo ""
  echo "❌ AI TRACES DETECTED - $TRACES_FOUND layers affected"
  echo "   Manual review required before deployment."
  exit 1
fi
