apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lydian-iq-api-hpa
  namespace: production
  labels:
    app: lydian-iq-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lydian-iq-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "1000"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
      selectPolicy: Max
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lydian-iq-config
  namespace: production
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  RATE_LIMIT_ENABLED: "true"
  CACHE_ENABLED: "true"
  CACHE_TTL: "300"
  MAX_REQUEST_SIZE: "10mb"
  CORS_ORIGIN: "https://ailydian.com,https://www.ailydian.com"
