/**
 * 🛡️ AILYDIAN SOC - MITRE ATT&CK Integration v13
 * Complete MITRE Knowledge Base, TTP mapping, heat map generation, tactic classification
 * © Emrah Şardağ. All rights reserved.
 */

import { MitreTactic, MitreTechnique, MitreSubTechnique, TtpHeatMap } from './schema';
import { SessionCluster } from './correlate';

export interface MITREMapping {
  tactics: string[];
  techniques: string[];
  confidence: number;
  description?: string;
}

export interface MITRETechnique {
  id: string;
  name: string;
  tactic: string[];
  description: string;
  platforms: string[];
  dataSources: string[];
  defenses: string[];
  detectionMethods: string[];
}

export interface MITRETactic {
  id: string;
  name: string;
  description: string;
  techniques: string[];
}

export class MITREAttackEngine {
  private static instance: MITREAttackEngine;
  private techniques: Map<string, MITRETechnique> = new Map();
  private tactics: Map<string, MITRETactic> = new Map();
  private eventPatterns: Map<string, MITREMapping> = new Map();

  private constructor() {
    this.initializeMITREData();
  }

  static getInstance(): MITREAttackEngine {
    if (!MITREAttackEngine.instance) {
      MITREAttackEngine.instance = new MITREAttackEngine();
    }
    return MITREAttackEngine.instance;
  }

  /**
   * Analyze security event and map to MITRE ATT&CK framework
   */
  async analyzeEvent(event: any): Promise<MITREMapping> {
    const mapping: MITREMapping = {
      tactics: [],
      techniques: [],
      confidence: 0
    };

    // Pattern-based analysis
    const patternMatches = this.analyzeEventPatterns(event);
    if (patternMatches.length > 0) {
      patternMatches.forEach(match => {
        mapping.tactics.push(...match.tactics);
        mapping.techniques.push(...match.techniques);
        mapping.confidence = Math.max(mapping.confidence, match.confidence);
      });
    }

    // Behavioral analysis
    const behaviorMapping = this.analyzeBehavior(event);
    if (behaviorMapping) {
      mapping.tactics.push(...behaviorMapping.tactics);
      mapping.techniques.push(...behaviorMapping.techniques);
      mapping.confidence = Math.max(mapping.confidence, behaviorMapping.confidence);
    }

    // Remove duplicates
    mapping.tactics = [...new Set(mapping.tactics)];
    mapping.techniques = [...new Set(mapping.techniques)];

    return mapping;
  }

  /**
   * Get technique details by ID
   */
  getTechnique(techniqueId: string): MITRETechnique | null {
    return this.techniques.get(techniqueId) || null;
  }

  /**
   * Get tactic details by ID
   */
  getTactic(tacticId: string): MITRETactic | null {
    return this.tactics.get(tacticId) || null;
  }

  /**
   * Get all techniques for a tactic
   */
  getTechniquesForTactic(tacticId: string): MITRETechnique[] {
    const tactic = this.tactics.get(tacticId);
    if (!tactic) return [];

    return tactic.techniques
      .map(techId => this.techniques.get(techId))
      .filter(tech => tech !== undefined) as MITRETechnique[];
  }

  /**
   * Search techniques by name or description
   */
  searchTechniques(query: string): MITRETechnique[] {
    const lowercaseQuery = query.toLowerCase();
    return Array.from(this.techniques.values()).filter(tech =>
      tech.name.toLowerCase().includes(lowercaseQuery) ||
      tech.description.toLowerCase().includes(lowercaseQuery)
    );
  }

  /**
   * Generate MITRE Navigator layer
   */
  generateNavigatorLayer(techniques: string[], name: string = 'AILYDIAN Detection'): any {
    const layer = {
      name,
      version: '4.5',
      domain: 'enterprise-attack',
      description: 'Generated by AILYDIAN Security Operations Center',
      filters: {
        platforms: ['windows', 'linux', 'macos', 'web', 'cloud']
      },
      sorting: 0,
      layout: {
        layout: 'side',
        aggregateFunction: 'average',
        showID: false,
        showName: true,
        showAggregateScores: false,
        countUnscored: false
      },
      hideDisabled: false,
      techniques: techniques.map(techId => {
        const technique = this.techniques.get(techId);
        return {
          techniqueID: techId,
          tactic: technique?.tactic[0] || '',
          score: 1,
          color: '#ff6666',
          comment: `Detected by AILYDIAN SOC`,
          enabled: true,
          metadata: [],
          links: [],
          showSubtechniques: false
        };
      }),
      gradient: {
        colors: ['#ff6666', '#ffe766', '#8ec843'],
        minValue: 0,
        maxValue: 1
      },
      legendItems: []
    };

    return layer;
  }

  /**
   * Pattern-based event analysis
   */
  private analyzeEventPatterns(event: any): MITREMapping[] {
    const matches: MITREMapping[] = [];

    // Web application attacks
    if (event.type === 'web_attack') {
      if (event.normalized?.url?.includes('sql') || 
          event.raw?.payload?.match(/(union|select|insert|delete|update|drop)/i)) {
        matches.push({
          tactics: ['TA0001'], // Initial Access
          techniques: ['T1190'], // Exploit Public-Facing Application
          confidence: 0.8,
          description: 'SQL Injection attempt detected'
        });
      }

      if (event.raw?.payload?.match(/(<script|javascript:|onload|onerror)/i)) {
        matches.push({
          tactics: ['TA0001'], // Initial Access
          techniques: ['T1190'], // Exploit Public-Facing Application
          confidence: 0.7,
          description: 'Cross-Site Scripting attempt detected'
        });
      }

      if (event.normalized?.url?.match(/(\.\.\/|\.\.\\|%2e%2e%2f)/i)) {
        matches.push({
          tactics: ['TA0007'], // Discovery
          techniques: ['T1083'], // File and Directory Discovery
          confidence: 0.6,
          description: 'Directory traversal attempt detected'
        });
      }
    }

    // Authentication attacks
    if (event.type === 'authentication_failed') {
      matches.push({
        tactics: ['TA0006'], // Credential Access
        techniques: ['T1110'], // Brute Force
        confidence: 0.5,
        description: 'Authentication failure - possible brute force'
      });
    }

    // Network reconnaissance
    if (event.type === 'port_scan' || event.type === 'network_scan') {
      matches.push({
        tactics: ['TA0007'], // Discovery
        techniques: ['T1046'], // Network Service Scanning
        confidence: 0.7,
        description: 'Network scanning activity detected'
      });
    }

    // Data exfiltration
    if (event.type === 'large_data_transfer' || event.type === 'unusual_upload') {
      matches.push({
        tactics: ['TA0010'], // Exfiltration
        techniques: ['T1041'], // Exfiltration Over C2 Channel
        confidence: 0.6,
        description: 'Potential data exfiltration detected'
      });
    }

    // Persistence attempts
    if (event.type === 'file_modification' && 
        event.normalized?.url?.match(/(autostart|startup|cron|systemd)/i)) {
      matches.push({
        tactics: ['TA0003'], // Persistence
        techniques: ['T1543'], // Create or Modify System Process
        confidence: 0.7,
        description: 'Persistence mechanism modification detected'
      });
    }

    return matches;
  }

  /**
   * Behavioral analysis of events
   */
  private analyzeBehavior(event: any): MITREMapping | null {
    // Analyze event behavior patterns
    const suspicious = this.calculateSuspicionScore(event);
    
    if (suspicious > 0.7) {
      return {
        tactics: ['TA0005'], // Defense Evasion
        techniques: ['T1070'], // Indicator Removal on Host
        confidence: suspicious,
        description: 'Suspicious behavior pattern detected'
      };
    }

    return null;
  }

  /**
   * Calculate suspicion score based on event characteristics
   */
  private calculateSuspicionScore(event: any): number {
    let score = 0;

    // Unusual time patterns
    const hour = new Date(event.timestamp).getHours();
    if (hour < 6 || hour > 22) {
      score += 0.2; // Activity during off-hours
    }

    // Geographic anomalies
    if (event.normalized?.geolocation?.country && 
        !['US', 'GB', 'DE', 'FR', 'CA', 'AU'].includes(event.normalized.geolocation.country)) {
      score += 0.3; // Activity from uncommon countries
    }

    // User agent anomalies
    if (event.normalized?.userAgent) {
      if (event.normalized.userAgent.includes('bot') || 
          event.normalized.userAgent.includes('crawler') ||
          event.normalized.userAgent.includes('scanner')) {
        score += 0.4;
      }
    }

    // High frequency from same source
    // This would require historical data analysis
    
    return Math.min(score, 1.0);
  }

  /**
   * Initialize comprehensive MITRE ATT&CK v13 data
   */
  private initializeMITREData(): void {
    // Complete MITRE ATT&CK Tactics v13
    const tactics = [
      { id: 'TA0043', name: 'Reconnaissance', description: 'The adversary is gathering information to plan future operations.', techniques: [] },
      { id: 'TA0042', name: 'Resource Development', description: 'The adversary is establishing resources to support operations.', techniques: [] },
      { id: 'TA0001', name: 'Initial Access', description: 'The adversary is trying to get into your network.', techniques: [] },
      { id: 'TA0002', name: 'Execution', description: 'The adversary is trying to run malicious code.', techniques: [] },
      { id: 'TA0003', name: 'Persistence', description: 'The adversary is trying to maintain their foothold.', techniques: [] },
      { id: 'TA0004', name: 'Privilege Escalation', description: 'The adversary is trying to gain higher-level permissions.', techniques: [] },
      { id: 'TA0005', name: 'Defense Evasion', description: 'The adversary is trying to avoid being detected.', techniques: [] },
      { id: 'TA0006', name: 'Credential Access', description: 'The adversary is trying to steal account names and passwords.', techniques: [] },
      { id: 'TA0007', name: 'Discovery', description: 'The adversary is trying to figure out your environment.', techniques: [] },
      { id: 'TA0008', name: 'Lateral Movement', description: 'The adversary is trying to move through your environment.', techniques: [] },
      { id: 'TA0009', name: 'Collection', description: 'The adversary is trying to gather data of interest.', techniques: [] },
      { id: 'TA0011', name: 'Command and Control', description: 'The adversary is trying to communicate with compromised systems.', techniques: [] },
      { id: 'TA0010', name: 'Exfiltration', description: 'The adversary is trying to steal data.', techniques: [] },
      { id: 'TA0040', name: 'Impact', description: 'The adversary is trying to manipulate, interrupt, or destroy your systems and data.', techniques: [] }
    ];

    // Enhanced techniques for web applications and crypto platforms
    const techniques = [
      // Initial Access
      {
        id: 'T1190',
        name: 'Exploit Public-Facing Application',
        tactic: ['TA0001'],
        description: 'Exploiting weaknesses in Internet-facing applications including web apps, APIs, and services.',
        platforms: ['Linux', 'Windows', 'macOS', 'Web', 'Cloud', 'Containers'],
        dataSources: ['Application Log', 'Network Traffic', 'Web Application Firewall Logs'],
        defenses: ['Application Isolation', 'Input Validation', 'Web Application Firewall', 'Regular Security Updates'],
        detectionMethods: ['SQL injection pattern detection', 'XSS payload analysis', 'Anomalous HTTP requests', 'Error rate monitoring']
      },
      {
        id: 'T1566',
        name: 'Phishing',
        tactic: ['TA0001'],
        description: 'Sending phishing messages to gain access to victim systems, often targeting crypto platform users.',
        platforms: ['Linux', 'Windows', 'macOS', 'Web', 'Mobile'],
        dataSources: ['Email Gateway Logs', 'Web Traffic', 'DNS Logs', 'URL Analysis'],
        defenses: ['Email Security', 'User Training', 'URL Filtering', 'Multi-Factor Authentication'],
        detectionMethods: ['Suspicious email analysis', 'Domain reputation checks', 'Link analysis', 'User behavior anomalies']
      },
      {
        id: 'T1189',
        name: 'Drive-by Compromise',
        tactic: ['TA0001'],
        description: 'Compromising users through malicious websites or compromised legitimate sites.',
        platforms: ['Windows', 'macOS', 'Linux', 'Web'],
        dataSources: ['Web Traffic', 'DNS Logs', 'Browser Logs', 'Network Connection'],
        defenses: ['Browser Security', 'Content Security Policy', 'Ad Blockers', 'URL Filtering'],
        detectionMethods: ['Malicious URL detection', 'JavaScript analysis', 'Exploit kit signatures', 'Network traffic analysis']
      },

      // Credential Access
      {
        id: 'T1110',
        name: 'Brute Force',
        tactic: ['TA0006'],
        description: 'Using trial-and-error to guess credentials, common in crypto platform attacks.',
        platforms: ['Windows', 'Linux', 'macOS', 'Web', 'Cloud', 'Mobile'],
        dataSources: ['Authentication Logs', 'Web Server Logs', 'API Logs', 'Account Activity'],
        defenses: ['Account Lockout Policies', 'Rate Limiting', 'Multi-Factor Authentication', 'CAPTCHA'],
        detectionMethods: ['Failed login monitoring', 'Account lockout alerts', 'Rate-based detection', 'Credential stuffing patterns']
      },
      {
        id: 'T1555',
        name: 'Credentials from Password Stores',
        tactic: ['TA0006'],
        description: 'Extracting credentials from browser password stores and crypto wallet files.',
        platforms: ['Windows', 'macOS', 'Linux', 'Web'],
        dataSources: ['File Access', 'Process Monitoring', 'Registry Modification'],
        defenses: ['Application Control', 'Password Manager Security', 'File Encryption', 'Process Monitoring'],
        detectionMethods: ['Browser database access', 'Credential file access', 'Password dumping tools', 'Unusual file operations']
      },
      {
        id: 'T1552',
        name: 'Unsecured Credentials',
        tactic: ['TA0006'],
        description: 'Finding credentials in configuration files, environment variables, or code repositories.',
        platforms: ['Linux', 'Windows', 'macOS', 'Web', 'Cloud'],
        dataSources: ['File Access', 'Repository Monitoring', 'Configuration Analysis'],
        defenses: ['Secret Management', 'Code Review', 'File Permissions', 'Environment Security'],
        detectionMethods: ['Secret scanning', 'Configuration monitoring', 'Repository analysis', 'Environment variable tracking']
      },

      // Discovery
      {
        id: 'T1083',
        name: 'File and Directory Discovery',
        tactic: ['TA0007'],
        description: 'Enumerating files and directories to find sensitive data like crypto keys or trading algorithms.',
        platforms: ['Linux', 'macOS', 'Windows', 'Web'],
        dataSources: ['File Access Logs', 'Process Monitoring', 'Command Execution'],
        defenses: ['File Permissions', 'Access Controls', 'Monitoring'],
        detectionMethods: ['Directory enumeration', 'File access patterns', 'Automated scanning tools', 'Unusual file queries']
      },
      {
        id: 'T1046',
        name: 'Network Service Scanning',
        tactic: ['TA0007'],
        description: 'Scanning for network services to identify attack vectors and crypto infrastructure.',
        platforms: ['Linux', 'macOS', 'Windows', 'Network'],
        dataSources: ['Network Traffic', 'IDS/IPS Logs', 'Firewall Logs'],
        defenses: ['Network Segmentation', 'Intrusion Prevention', 'Port Filtering'],
        detectionMethods: ['Port scan detection', 'Service enumeration', 'Network mapping', 'Reconnaissance patterns']
      },
      {
        id: 'T1018',
        name: 'Remote System Discovery',
        tactic: ['TA0007'],
        description: 'Identifying remote systems in the network for lateral movement or targeting crypto nodes.',
        platforms: ['Linux', 'Windows', 'macOS', 'Network'],
        dataSources: ['Network Traffic', 'DNS Queries', 'ARP Tables'],
        defenses: ['Network Monitoring', 'DNS Security', 'Network Segmentation'],
        detectionMethods: ['Network discovery tools', 'DNS enumeration', 'ARP sweeping', 'Host discovery patterns']
      },
      {
        id: 'T1087',
        name: 'Account Discovery',
        tactic: ['TA0007'],
        description: 'Enumerating user accounts to identify high-value targets like admin or trading accounts.',
        platforms: ['Windows', 'macOS', 'Linux', 'Web', 'Cloud'],
        dataSources: ['Process Monitoring', 'API Logs', 'Authentication Logs'],
        defenses: ['Access Controls', 'Account Management', 'Audit Logging'],
        detectionMethods: ['User enumeration', 'LDAP queries', 'API enumeration', 'Account probing']
      },

      // Defense Evasion
      {
        id: 'T1070',
        name: 'Indicator Removal on Host',
        tactic: ['TA0005'],
        description: 'Deleting or modifying artifacts to hide malicious activity and trading manipulation.',
        platforms: ['Linux', 'macOS', 'Windows'],
        dataSources: ['File Monitoring', 'Process Monitoring', 'Log Analysis'],
        defenses: ['File Integrity Monitoring', 'Centralized Logging', 'Write Protection'],
        detectionMethods: ['Log tampering detection', 'File deletion monitoring', 'Timeline analysis', 'Artifact recovery']
      },
      {
        id: 'T1036',
        name: 'Masquerading',
        tactic: ['TA0005'],
        description: 'Disguising malicious activity as legitimate operations or trusted applications.',
        platforms: ['Linux', 'Windows', 'macOS', 'Web'],
        dataSources: ['File Monitoring', 'Process Monitoring', 'Network Traffic'],
        defenses: ['Application Whitelisting', 'Code Signing', 'Behavioral Analysis'],
        detectionMethods: ['Suspicious process names', 'File hash analysis', 'Certificate validation', 'Behavior comparison']
      },
      {
        id: 'T1027',
        name: 'Obfuscated Files or Information',
        tactic: ['TA0005'],
        description: 'Hiding malicious code or data through encoding, encryption, or compression.',
        platforms: ['Linux', 'Windows', 'macOS', 'Web'],
        dataSources: ['File Monitoring', 'Network Traffic', 'Process Monitoring'],
        defenses: ['Content Analysis', 'Behavioral Detection', 'Sandbox Analysis'],
        detectionMethods: ['Entropy analysis', 'Encoding detection', 'Packed executable analysis', 'Obfuscation patterns']
      },

      // Impact
      {
        id: 'T1498',
        name: 'Network Denial of Service',
        tactic: ['TA0040'],
        description: 'Performing DoS attacks against network infrastructure to disrupt trading or platform access.',
        platforms: ['Network', 'Linux', 'Windows', 'macOS'],
        dataSources: ['Network Traffic', 'Network Device Logs', 'Application Performance'],
        defenses: ['DDoS Protection', 'Rate Limiting', 'Traffic Shaping', 'Load Balancing'],
        detectionMethods: ['Traffic volume analysis', 'Connection rate monitoring', 'Bandwidth usage', 'Service availability']
      },
      {
        id: 'T1499',
        name: 'Endpoint Denial of Service',
        tactic: ['TA0040'],
        description: 'Exhausting endpoint resources to disrupt crypto trading applications or wallet access.',
        platforms: ['Linux', 'Windows', 'macOS', 'Web'],
        dataSources: ['Process Monitoring', 'System Resource Usage', 'Application Logs'],
        defenses: ['Resource Monitoring', 'Rate Limiting', 'Process Controls'],
        detectionMethods: ['CPU/memory exhaustion', 'Application slowdown', 'Resource starvation', 'Service degradation']
      },
      {
        id: 'T1565',
        name: 'Data Manipulation',
        tactic: ['TA0040'],
        description: 'Manipulating data to affect business decisions, particularly dangerous in trading environments.',
        platforms: ['Linux', 'Windows', 'macOS', 'Web', 'Cloud'],
        dataSources: ['Application Logs', 'Database Logs', 'File Integrity'],
        defenses: ['Data Integrity Controls', 'Database Security', 'Access Controls', 'Change Management'],
        detectionMethods: ['Data validation checks', 'Integrity monitoring', 'Audit trail analysis', 'Anomaly detection']
      },

      // Command and Control
      {
        id: 'T1071',
        name: 'Application Layer Protocol',
        tactic: ['TA0011'],
        description: 'Using application layer protocols for C2 communication, often mimicking legitimate crypto API traffic.',
        platforms: ['Linux', 'Windows', 'macOS', 'Web'],
        dataSources: ['Network Traffic', 'Netflow Data', 'Proxy Logs'],
        defenses: ['Network Monitoring', 'Protocol Analysis', 'Traffic Filtering'],
        detectionMethods: ['Protocol anomaly detection', 'Traffic pattern analysis', 'C2 beacon detection', 'Domain analysis']
      },
      {
        id: 'T1573',
        name: 'Encrypted Channel',
        tactic: ['TA0011'],
        description: 'Using encryption to hide C2 communications within legitimate encrypted traffic.',
        platforms: ['Linux', 'Windows', 'macOS', 'Network'],
        dataSources: ['Network Traffic', 'SSL/TLS Logs', 'Certificate Analysis'],
        defenses: ['SSL/TLS Inspection', 'Certificate Monitoring', 'Traffic Analysis'],
        detectionMethods: ['Certificate anomalies', 'Encryption pattern analysis', 'Traffic metadata', 'JA3/JA3S fingerprinting']
      },

      // Collection & Exfiltration
      {
        id: 'T1005',
        name: 'Data from Local System',
        tactic: ['TA0009'],
        description: 'Collecting sensitive data like crypto keys, trading data, or personal information from local systems.',
        platforms: ['Linux', 'Windows', 'macOS'],
        dataSources: ['File Access', 'Process Monitoring', 'Data Loss Prevention'],
        defenses: ['Data Loss Prevention', 'File Monitoring', 'Access Controls'],
        detectionMethods: ['Sensitive file access', 'Data collection tools', 'Unusual file operations', 'Data staging']
      },
      {
        id: 'T1041',
        name: 'Exfiltration Over C2 Channel',
        tactic: ['TA0010'],
        description: 'Stealing data over existing C2 channels, particularly dangerous for trading algorithms or private keys.',
        platforms: ['Linux', 'macOS', 'Windows'],
        dataSources: ['Network Traffic', 'File Access', 'Process Monitoring'],
        defenses: ['Data Loss Prevention', 'Network Monitoring', 'Egress Filtering'],
        detectionMethods: ['Unusual outbound traffic', 'Data size analysis', 'Transfer timing patterns', 'C2 channel monitoring']
      }
    ];

    // Store in maps
    tactics.forEach(tactic => this.tactics.set(tactic.id, tactic));
    techniques.forEach(technique => this.techniques.set(technique.id, technique));

    // Update tactic-technique relationships
    techniques.forEach(technique => {
      technique.tactic.forEach(tacticId => {
        const tactic = this.tactics.get(tacticId);
        if (tactic) {
          tactic.techniques.push(technique.id);
        }
      });
    });
  }

  /**
   * Get all tactics
   */
  getAllTactics(): MITRETactic[] {
    return Array.from(this.tactics.values());
  }

  /**
   * Get all techniques
   */
  getAllTechniques(): MITRETechnique[] {
    return Array.from(this.techniques.values());
  }

  /**
   * Export current detections as MITRE Navigator layer
   */
  exportNavigatorLayer(detectedTechniques: string[]): string {
    const layer = this.generateNavigatorLayer(detectedTechniques);
    return JSON.stringify(layer, null, 2);
  }
}

/**
 * Enhanced TTP (Tactics, Techniques, Procedures) Mapper for SOC Integration
 */
export class TTPMapper {
  private mitreEngine: MITREAttackEngine;

  constructor(mitreEngine: MITREAttackEngine) {
    this.mitreEngine = mitreEngine;
  }

  /**
   * Map session cluster to potential TTPs with enhanced crypto-specific analysis
   */
  mapSessionToTTPs(cluster: SessionCluster): Array<{
    technique: MITRETechnique;
    confidence: number;
    evidence: string[];
    subTechniques?: string[];
  }> {
    const mappings: Array<{
      technique: MITRETechnique;
      confidence: number;
      evidence: string[];
      subTechniques?: string[];
    }> = [];

    // Pattern-based TTP mapping
    for (const pattern of cluster.patterns) {
      const ttpMappings = this.mapPatternToTTPs(pattern, cluster);
      mappings.push(...ttpMappings);
    }

    // Behavioral analysis for crypto-specific threats
    const behaviorMappings = this.analyzeCryptoBehaviorForTTPs(cluster);
    mappings.push(...behaviorMappings);

    // Route analysis for web application attacks
    const routeMappings = this.analyzeRoutesForTTPs(cluster);
    mappings.push(...routeMappings);

    // Temporal analysis for advanced persistent threats
    const temporalMappings = this.analyzeTemporalPatternsForTTPs(cluster);
    mappings.push(...temporalMappings);

    // Deduplicate and sort by confidence
    const uniqueMappings = this.deduplicateTTPs(mappings);
    return uniqueMappings.sort((a, b) => b.confidence - a.confidence);
  }

  /**
   * Map specific patterns to TTPs with enhanced detection
   */
  private mapPatternToTTPs(pattern: string, cluster: SessionCluster): Array<{
    technique: MITRETechnique;
    confidence: number;
    evidence: string[];
    subTechniques?: string[];
  }> {
    const mappings: Array<{
      technique: MITRETechnique;
      confidence: number;
      evidence: string[];
      subTechniques?: string[];
    }> = [];

    switch (pattern) {
      case 'BRUTE_FORCE_ATTEMPT':
        const bruteForceTechnique = this.mitreEngine.getTechnique('T1110');
        if (bruteForceTechnique) {
          const subTechniques = this.identifyBruteForceSubTechniques(cluster);
          mappings.push({
            technique: bruteForceTechnique,
            confidence: Math.min(0.95, 0.7 + (cluster.eventCount / 1000) * 0.25),
            evidence: [
              `High frequency authentication attempts: ${cluster.eventCount} events`,
              `Multiple source IPs: ${cluster.uniqueIPs.size} addresses`,
              `Authentication endpoints targeted: ${[...cluster.uniqueRoutes].filter(r => r.includes('auth') || r.includes('login')).length}`,
              `Time span: ${Math.round((cluster.lastSeen.getTime() - cluster.firstSeen.getTime()) / 60000)} minutes`,
            ],
            subTechniques,
          });
        }
        break;

      case 'ROUTE_ENUMERATION':
        const discoveryTechnique = this.mitreEngine.getTechnique('T1083');
        if (discoveryTechnique) {
          mappings.push({
            technique: discoveryTechnique,
            confidence: Math.min(0.9, 0.6 + (cluster.uniqueRoutes.size / 100) * 0.3),
            evidence: [
              `Systematic endpoint enumeration: ${cluster.uniqueRoutes.size} unique routes`,
              `Directory traversal patterns detected`,
              `API endpoint discovery patterns`,
              `Response code analysis: ${this.analyzeResponseCodes(cluster)}`,
            ],
          });
        }
        break;

      case 'HIGH_FREQUENCY_REQUESTS':
        const dosTechnique = this.mitreEngine.getTechnique('T1499');
        if (dosTechnique) {
          mappings.push({
            technique: dosTechnique,
            confidence: 0.8,
            evidence: [
              `Abnormally high request frequency: ${Math.round(cluster.eventCount / ((cluster.lastSeen.getTime() - cluster.firstSeen.getTime()) / 60000))} req/min`,
              `Potential application resource exhaustion`,
              `Sustained attack duration: ${Math.round((cluster.lastSeen.getTime() - cluster.firstSeen.getTime()) / 60000)} minutes`,
            ],
            subTechniques: ['T1499.004'], // Application Exhaustion Flood
          });
        }
        break;

      case 'DISTRIBUTED_ATTACK':
        const networkDosTechnique = this.mitreEngine.getTechnique('T1498');
        if (networkDosTechnique) {
          mappings.push({
            technique: networkDosTechnique,
            confidence: 0.85,
            evidence: [
              `Distributed attack pattern from ${cluster.uniqueIPs.size} unique IPs`,
              `Coordinated network activity detected`,
              `Geographic distribution analysis needed`,
              `Potential botnet indicators`,
            ],
            subTechniques: ['T1498.001', 'T1498.002'], // Direct Network Flood, Reflection Amplification
          });
        }
        break;

      case 'HIGH_ERROR_RATE':
        const exploitTechnique = this.mitreEngine.getTechnique('T1190');
        if (exploitTechnique) {
          mappings.push({
            technique: exploitTechnique,
            confidence: 0.7,
            evidence: [
              `High error rate suggesting exploitation attempts`,
              `Web application vulnerability probing`,
              `Error-based attack pattern recognition`,
              `Potential SQL injection or XSS attempts`,
            ],
            subTechniques: this.identifyWebAttackSubTechniques(cluster),
          });
        }
        break;

      case 'CREDENTIAL_STUFFING':
        const credStuffingTechnique = this.mitreEngine.getTechnique('T1110');
        if (credStuffingTechnique) {
          mappings.push({
            technique: credStuffingTechnique,
            confidence: 0.9,
            evidence: [
              `Credential stuffing pattern detected`,
              `Multiple IPs using known credential pairs`,
              `Login endpoint targeting with credential rotation`,
              `Potential use of compromised credential databases`,
            ],
            subTechniques: ['T1110.004'], // Credential Stuffing
          });
        }
        break;
    }

    return mappings;
  }

  /**
   * Analyze crypto-specific behavioral patterns
   */
  private analyzeCryptoBehaviorForTTPs(cluster: SessionCluster): Array<{
    technique: MITRETechnique;
    confidence: number;
    evidence: string[];
    subTechniques?: string[];
  }> {
    const mappings: Array<{
      technique: MITRETechnique;
      confidence: number;
      evidence: string[];
      subTechniques?: string[];
    }> = [];

    // Check for wallet/key-related reconnaissance  
    const cryptoRoutes = [...cluster.uniqueRoutes].filter(route => 
      route.match(/(wallet|key|crypto|btc|eth|trade|exchange|balance|withdraw|deposit)/i)
    );
    
    if (cryptoRoutes.length > 10) {
      const reconTechnique = this.mitreEngine.getTechnique('T1087'); // Account Discovery
      if (reconTechnique) {
        mappings.push({
          technique: reconTechnique,
          confidence: 0.8,
          evidence: [
            `Crypto-related endpoint enumeration: ${cryptoRoutes.length} routes`,
            `Potential wallet/account discovery attempts`,
            `Trading platform reconnaissance detected`,
          ],
        });
      }
    }

    // Check for API key harvesting attempts
    const apiRoutes = [...cluster.uniqueRoutes].filter(route => 
      route.includes('api') && (route.includes('key') || route.includes('token') || route.includes('auth'))
    );
    
    if (apiRoutes.length > 5) {
      const credAccessTechnique = this.mitreEngine.getTechnique('T1552'); // Unsecured Credentials
      if (credAccessTechnique) {
        mappings.push({
          technique: credAccessTechnique,
          confidence: 0.85,
          evidence: [
            `API credential harvesting attempt detected`,
            `Multiple API authentication endpoints targeted`,
            `Potential API key enumeration patterns`,
          ],
        });
      }
    }

    // Check for trading manipulation patterns
    if (this.detectTradingManipulation(cluster)) {
      const manipulationTechnique = this.mitreEngine.getTechnique('T1565'); // Data Manipulation
      if (manipulationTechnique) {
        mappings.push({
          technique: manipulationTechnique,
          confidence: 0.75,
          evidence: [
            `Potential trading data manipulation detected`,
            `Market manipulation indicators present`,
            `Automated trading bot activity suspected`,
          ],
        });
      }
    }

    return mappings;
  }

  /**
   * Analyze routes for specific attack patterns
   */
  private analyzeRoutesForTTPs(cluster: SessionCluster): Array<{
    technique: MITRETechnique;
    confidence: number;
    evidence: string[];
    subTechniques?: string[];
  }> {
    const mappings: Array<{
      technique: MITRETechnique;
      confidence: number;
      evidence: string[];
      subTechniques?: string[];
    }> = [];

    const routes = [...cluster.uniqueRoutes];

    // SQL Injection patterns
    const sqlRoutes = routes.filter(route => 
      route.match(/(union|select|insert|delete|update|drop|exec|sp_|xp_|'|"|;|--)/i)
    );
    
    if (sqlRoutes.length > 0) {
      const sqlTechnique = this.mitreEngine.getTechnique('T1190');
      if (sqlTechnique) {
        mappings.push({
          technique: sqlTechnique,
          confidence: 0.9,
          evidence: [
            `SQL injection patterns detected: ${sqlRoutes.length} routes`,
            `Database manipulation attempts`,
            `Potential data exfiltration via SQL`,
          ],
          subTechniques: ['T1190.001'], // SQL Injection sub-technique
        });
      }
    }

    // XSS patterns
    const xssRoutes = routes.filter(route => 
      route.match(/(<script|javascript:|onload|onerror|alert|eval|document\.)/i)
    );
    
    if (xssRoutes.length > 0) {
      const xssTechnique = this.mitreEngine.getTechnique('T1190');
      if (xssTechnique) {
        mappings.push({
          technique: xssTechnique,
          confidence: 0.85,
          evidence: [
            `Cross-Site Scripting patterns detected: ${xssRoutes.length} routes`,
            `Client-side code injection attempts`,
            `Potential session hijacking preparation`,
          ],
          subTechniques: ['T1190.002'], // XSS sub-technique
        });
      }
    }

    // Directory traversal patterns
    const traversalRoutes = routes.filter(route => 
      route.match(/(\.\.\/|\.\.\\|%2e%2e%2f|%2e%2e%5c|\.\.%2f)/i)
    );
    
    if (traversalRoutes.length > 0) {
      const traversalTechnique = this.mitreEngine.getTechnique('T1083');
      if (traversalTechnique) {
        mappings.push({
          technique: traversalTechnique,
          confidence: 0.8,
          evidence: [
            `Directory traversal attempts: ${traversalRoutes.length} routes`,
            `Unauthorized file access attempts`,
            `Potential system file enumeration`,
          ],
        });
      }
    }

    return mappings;
  }

  /**
   * Analyze temporal patterns for APT indicators
   */
  private analyzeTemporalPatternsForTTPs(cluster: SessionCluster): Array<{
    technique: MITRETechnique;
    confidence: number;
    evidence: string[];
    subTechniques?: string[];
  }> {
    const mappings: Array<{
      technique: MITRETechnique;
      confidence: number;
      evidence: string[];
      subTechniques?: string[];
    }> = [];

    const duration = cluster.lastSeen.getTime() - cluster.firstSeen.getTime();
    const avgInterval = duration / cluster.eventCount;

    // Check for low-and-slow attacks (potential APT)
    if (duration > 3600000 && avgInterval > 60000) { // > 1 hour, avg > 1 min intervals
      const evasionTechnique = this.mitreEngine.getTechnique('T1070');
      if (evasionTechnique) {
        mappings.push({
          technique: evasionTechnique,
          confidence: 0.6,
          evidence: [
            `Low-and-slow attack pattern detected`,
            `Extended duration: ${Math.round(duration / 3600000)} hours`,
            `Evasive timing patterns to avoid detection`,
            `Potential advanced persistent threat indicators`,
          ],
        });
      }
    }

    // Check for coordinated timing (potential botnet)
    if (cluster.uniqueIPs.size > 10 && this.hasCoordinatedTiming(cluster)) {
      const c2Technique = this.mitreEngine.getTechnique('T1071');
      if (c2Technique) {
        mappings.push({
          technique: c2Technique,
          confidence: 0.75,
          evidence: [
            `Coordinated timing patterns detected`,
            `Multiple IPs with synchronized activity`,
            `Potential command and control coordination`,
            `Botnet activity indicators`,
          ],
        });
      }
    }

    return mappings;
  }

  /**
   * Helper methods for enhanced analysis
   */
  private identifyBruteForceSubTechniques(cluster: SessionCluster): string[] {
    const subTechniques: string[] = [];
    
    if (cluster.uniqueIPs.size > 100) {
      subTechniques.push('T1110.003'); // Password Spraying
    }
    
    if (cluster.eventCount / cluster.uniqueIPs.size > 10) {
      subTechniques.push('T1110.001'); // Password Guessing
    }
    
    return subTechniques;
  }

  private identifyWebAttackSubTechniques(cluster: SessionCluster): string[] {
    const subTechniques: string[] = [];
    const routes = [...cluster.uniqueRoutes].join(' ').toLowerCase();
    
    if (routes.includes('sql') || routes.match(/(union|select|insert)/)) {
      subTechniques.push('T1190.001'); // SQL Injection
    }
    
    if (routes.includes('script') || routes.includes('javascript')) {
      subTechniques.push('T1190.002'); // XSS
    }
    
    return subTechniques;
  }

  private analyzeResponseCodes(_cluster: SessionCluster): string {
    // Placeholder for response code analysis
    return 'Mixed 4xx/5xx responses indicating probing';
  }

  private detectTradingManipulation(cluster: SessionCluster): boolean {
    const tradingRoutes = [...cluster.uniqueRoutes].filter(route => 
      route.match(/(trade|order|buy|sell|price|market|volume)/i)
    );
    
    return tradingRoutes.length > 20 && cluster.eventCount > 500;
  }

  private hasCoordinatedTiming(_cluster: SessionCluster): boolean {
    // Placeholder for timing correlation analysis
    // Would analyze event timestamps for synchronization patterns
    return false;
  }

  /**
   * Remove duplicate TTP mappings and merge evidence
   */
  private deduplicateTTPs(mappings: Array<{
    technique: MITRETechnique;
    confidence: number;
    evidence: string[];
    subTechniques?: string[];
  }>): Array<{
    technique: MITRETechnique;
    confidence: number;
    evidence: string[];
    subTechniques?: string[];
  }> {
    const seen = new Map<string, {
      technique: MITRETechnique;
      confidence: number;
      evidence: string[];
      subTechniques?: string[];
    }>();

    for (const mapping of mappings) {
      const key = mapping.technique.id;
      const existing = seen.get(key);
      
      if (!existing || mapping.confidence > existing.confidence) {
        const mergedSubTechniques = [
          ...(existing?.subTechniques || []),
          ...(mapping.subTechniques || []),
        ];
        
        seen.set(key, {
          ...mapping,
          evidence: existing ? 
            [...existing.evidence, ...mapping.evidence] : 
            mapping.evidence,
          subTechniques: [...new Set(mergedSubTechniques)],
        });
      }
    }

    return Array.from(seen.values());
  }
}

/**
 * MITRE ATT&CK Heat Map Generator for SOC Dashboard
 */
export class MitreHeatMapGenerator {
  private mitreEngine: MITREAttackEngine;

  constructor(mitreEngine: MITREAttackEngine) {
    this.mitreEngine = mitreEngine;
  }

  /**
   * Generate comprehensive heat map from TTP findings
   */
  generateHeatMap(
    findings: Array<{
      ttp: string;
      risk: number;
      timestamp: Date;
      subTechniques?: string[];
      confidence?: number;
    }>,
    timeRangeHours = 24
  ): TtpHeatMap[] {
    const cutoffTime = new Date(Date.now() - timeRangeHours * 60 * 60 * 1000);
    
    // Filter recent findings
    const recentFindings = findings.filter(f => f.timestamp > cutoffTime);
    
    // Group by TTP
    const ttpGroups = new Map<string, Array<typeof findings[0]>>();
    
    for (const finding of recentFindings) {
      if (!ttpGroups.has(finding.ttp)) {
        ttpGroups.set(finding.ttp, []);
      }
      ttpGroups.get(finding.ttp)!.push(finding);
    }

    // Generate heat map entries
    const heatMap: TtpHeatMap[] = [];
    
    for (const [ttp, ttpFindings] of ttpGroups) {
      const technique = this.mitreEngine.getTechnique(ttp);
      if (!technique) continue;

      const count = ttpFindings.length;
      const avgRisk = ttpFindings.reduce((sum, f) => sum + f.risk, 0) / count;
      const avgConfidence = ttpFindings.reduce((sum, f) => sum + (f.confidence || 0.5), 0) / count;
      const lastSeen = new Date(Math.max(...ttpFindings.map(f => f.timestamp.getTime())));

      // Calculate composite score (risk + confidence + frequency)
      const frequency = count / 24; // events per hour
      const compositeScore = (avgRisk * 0.4) + (avgConfidence * 0.3) + Math.min(frequency * 0.3, 1.0);

      heatMap.push({
        tactic: technique.tactic[0] || 'Unknown',
        technique: technique.name,
        ttp: technique.id,
        count,
        avgRisk: avgRisk,
        lastSeen,
        compositeScore,
        avgConfidence,
        frequency,
      } as TtpHeatMap);
    }

    return heatMap.sort((a, b) => (b.compositeScore || 0) - (a.compositeScore || 0));
  }

  /**
   * Generate matrix view optimized for SOC dashboard
   */
  generateMatrix(heatMap: TtpHeatMap[]): Array<{
    tactic: string;
    tacticId: string;
    techniques: Array<{
      id: string;
      name: string;
      count: number;
      avgRisk: number;
      intensity: number; // 0-100 for color mapping
      lastSeen: Date;
      compositeScore: number;
      threatLevel: 'low' | 'medium' | 'high' | 'critical';
      subTechniques?: string[];
    }>;
    tacticThreatLevel: 'low' | 'medium' | 'high' | 'critical';
    tacticCount: number;
  }> {
    const tactics = this.mitreEngine.getAllTactics();
    const matrix: Array<{
      tactic: string;
      tacticId: string;
      techniques: Array<{
        id: string;
        name: string;
        count: number;
        avgRisk: number;
        intensity: number;
        lastSeen: Date;
        compositeScore: number;
        threatLevel: 'low' | 'medium' | 'high' | 'critical';
        subTechniques?: string[];
      }>;
      tacticThreatLevel: 'low' | 'medium' | 'high' | 'critical';
      tacticCount: number;
    }> = [];

    // Find max values for normalization
    const maxCount = Math.max(...heatMap.map(h => h.count), 1);
    const maxComposite = Math.max(...heatMap.map(h => h.compositeScore || 0), 1);

    for (const tactic of tactics) {
      const tacticTechniques = heatMap
        .filter(h => h.tactic === tactic.name)
        .map(h => {
          const intensity = Math.round((h.compositeScore || 0) / maxComposite * 100);
          const threatLevel = this.calculateThreatLevel(h.compositeScore || 0, h.avgRisk);
          
          return {
            id: h.ttp,
            name: h.technique,
            count: h.count,
            avgRisk: h.avgRisk,
            intensity,
            lastSeen: h.lastSeen,
            compositeScore: h.compositeScore || 0,
            threatLevel,
            subTechniques: [], // Could be populated from findings
          };
        });

      const tacticCount = tacticTechniques.reduce((sum, t) => sum + t.count, 0);
      const tacticMaxThreat = tacticTechniques.reduce((max, t) => {
        const levels = ['low', 'medium', 'high', 'critical'];
        const maxIndex = Math.max(levels.indexOf(max), levels.indexOf(t.threatLevel));
        return levels[maxIndex] as 'low' | 'medium' | 'high' | 'critical';
      }, 'low' as 'low' | 'medium' | 'high' | 'critical');

      matrix.push({
        tactic: tactic.name,
        tacticId: tactic.id,
        techniques: tacticTechniques,
        tacticThreatLevel: tacticMaxThreat,
        tacticCount,
      });
    }

    return matrix.sort((a, b) => {
      const threatOrder = ['low', 'medium', 'high', 'critical'];
      return threatOrder.indexOf(b.tacticThreatLevel) - threatOrder.indexOf(a.tacticThreatLevel);
    });
  }

  /**
   * Calculate threat level based on composite score and risk
   */
  private calculateThreatLevel(compositeScore: number, avgRisk: number): 'low' | 'medium' | 'high' | 'critical' {
    if (compositeScore >= 0.8 || avgRisk >= 0.9) return 'critical';
    if (compositeScore >= 0.6 || avgRisk >= 0.7) return 'high';
    if (compositeScore >= 0.4 || avgRisk >= 0.5) return 'medium';
    return 'low';
  }

  /**
   * Generate trend data for time series analysis
   */
  generateTrendData(
    findings: Array<{
      ttp: string;
      risk: number;
      timestamp: Date;
    }>,
    timeRangeHours = 24,
    intervalMinutes = 60
  ): Array<{
    timestamp: Date;
    tacticCounts: Record<string, number>;
    totalEvents: number;
    avgRisk: number;
    topTechniques: string[];
  }> {
    const cutoffTime = new Date(Date.now() - timeRangeHours * 60 * 60 * 1000);
    const intervalMs = intervalMinutes * 60 * 1000;
    
    const recentFindings = findings.filter(f => f.timestamp > cutoffTime);
    const trends: Array<{
      timestamp: Date;
      tacticCounts: Record<string, number>;
      totalEvents: number;
      avgRisk: number;
      topTechniques: string[];
    }> = [];

    // Create time buckets
    for (let time = cutoffTime.getTime(); time < Date.now(); time += intervalMs) {
      const bucketStart = new Date(time);
      const bucketEnd = new Date(time + intervalMs);
      
      const bucketFindings = recentFindings.filter(f => 
        f.timestamp >= bucketStart && f.timestamp < bucketEnd
      );

      const tacticCounts: Record<string, number> = {};
      const techniqueCounts: Record<string, number> = {};

      for (const finding of bucketFindings) {
        const technique = this.mitreEngine.getTechnique(finding.ttp);
        if (technique) {
          const tactic = technique.tactic[0] || 'Unknown';
          tacticCounts[tactic] = (tacticCounts[tactic] || 0) + 1;
          techniqueCounts[finding.ttp] = (techniqueCounts[finding.ttp] || 0) + 1;
        }
      }

      const avgRisk = bucketFindings.length > 0 
        ? bucketFindings.reduce((sum, f) => sum + f.risk, 0) / bucketFindings.length
        : 0;

      const topTechniques = Object.entries(techniqueCounts)
        .sort(([,a], [,b]) => b - a)
        .slice(0, 5)
        .map(([ttp]) => ttp);

      trends.push({
        timestamp: bucketStart,
        tacticCounts,
        totalEvents: bucketFindings.length,
        avgRisk,
        topTechniques,
      });
    }

    return trends;
  }
}

// Singleton instance
export const mitreAttackEngine = MITREAttackEngine.getInstance();
